---
- hosts: webservers
  tasks:
    - name: Install package
      yum: name=libselinux-python state=present

    - name: install webserver
      yum: name=httpd state=present

    - name: create content
      copy: src=index.html dest=/var/www/html/index.html

    - name: start webserver (also on boot)
      service: name=httpd state=running enabled=yes
